FROM fusuf/whatsasena:latest

RUN git clone https://github.com/zim-bot/zimbot-v4 /Drips/Zimbotv4

WORKDIR /Drips/Zimbotv4

ENV TZ=Africa/Harare

RUN npm install

RUN npm install supervisor -g
RUN yarn install --ignore-engines
CMD ["node", "index.js"]
knok0ki

knok0ki

j90kijonommb9jo 9kn
j9pnij9

j9pnij9

